name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or 'master', based on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages   # The branch where your site will be deployed
        folder: .           # The folder containing your static files (use '.' for root)
